# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96358b2be7ecc3430b2efcad487e1820c396d225cec34f0de7b6e67f9524c38c0eb767a1b61aa0d31044cf9ba88fb5fc51327edde970b05c2e6a4b7ead5a6dd4

test:
  secret_key_base: cb41b499682ba2f19dd11ddf1258d3d4ccb647a27c913b434ac94e0f80fefebf366093b11077c096c378688e325effd73a378b1766068626df99e67eeb2831be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
